### ISSUE TITLE
Hi, explore++ crash when right click on win10_64 sometimes, not everytime

### ISSUE THREAD

**Issue by nottellyou** [derceg/explorerplusplus#65] opened 2017-05-16 09:25 UTC
Hi, explore++ crash when right click on win10_64 sometimes, not everytime

**Comment by derceg** [comment] 2017-06-03 07:58
It sounds like this is a duplicate of #35. If possible, can you try disabling OneDrive and see if that helps?

**Comment by Ashark** [comment] 2017-08-24 20:40
As for me, it was crashing on win10_64 when right click in empty space everywhere besides root "My computer" folder.
It was not possible to delete C:\Users\username\AppData\Local\Microsoft\OneDrive neither directly (even with admin privilages) nor with `rd "%LocalAppData%\Microsoft\OneDrive" /Q /S` command. It said that files inside were in use by Explorer and permission was denied.
**I booted to Linux, mounted windows partition and removed that folder.** Then booted to windows.
It worked. Explorer++ do not crashes anymore.

**Comment by nguyendangdung** [comment] 2018-01-27 04:44
Run the app as Administrator then the crash has gone

**Comment by nottellyou** [comment] 2018-01-30 07:43
Now I remove the OneDrive , it seems working fine.

**Comment by Squelsh** [comment] 2018-12-19 09:47
Can confirm that. Works when OneDrive is removed.
@Ashark I used the standard deinstallation from the system settings to get rid of OneDrive without hassle.

**Closed** 2018-12-24 10:10 UTC
Labels: bug, duplicate
