### ISSUE TITLE
default columns dialog does not save changes

### ISSUE THREAD

**Issue by sean-e** [derceg/explorerplusplus#215] opened 2020-04-25 03:26 UTC
- Tools | Options | Default Settings | Default Columns | Details
- Uncheck an item
- Change the order of the first two items
- press ok
- press ok
- Tools | Options | Default Settings | Default Columns | Details

Item that was unchecked is no longer unchecked.
Default order is back.

1.4.0.1592

**Comment by jczanfona** [comment] 2020-04-25 14:17
Solved with [v1.4.0.1594](https://github.com/derceg/explorerplusplus#latest-builds)
Can you test it?

**Comment by sean-e** [comment] 2020-04-25 21:43
> Solved with [v1.4.0.1594](https://github.com/derceg/explorerplusplus#latest-builds)
> Can you test it?

What is the basis for your statement that it was solved?
What change fixed it (aside from my pull request)?

**Comment by jczanfona** [comment] 2020-04-26 08:02
In the tests I did, it seemed to me that the problem was solved.

**Comment by sean-e** [comment] 2020-04-26 12:51
Interesting.  Perhaps my steps to repro are dependent on some other default state as I've only used Exp++ for less than a week.

**Comment by jczanfona** [comment] 2020-04-27 07:26
Remember to press in the menu: View - Save Column Layout as Default" with only have one tab, and then try to open others.
Last version is [v1.4.0.1606](https://github.com/derceg/explorerplusplus#latest-builds)

If you think the problem is solved, you can close this ticket.

**Comment by sean-e** [comment] 2020-04-27 14:45
That is a workaround for the bug for which I have described and offered a fix via the PR.

**Closed** 2020-10-31 22:58 UTC
