### ISSUE TITLE
Non-existent drives appear

### ISSUE THREAD

**Issue by CanuckGamer** [derceg/explorerplusplus#170] opened 2019-10-22 18:52 UTC
Below the address bar, and above where the tabs appear, is a bar that shows the drive on the computer.

When I open explorer I correctly see:
C:  D:  E:  G:  H:  K:  N:  P:  S:

But over time I see "U:" drives appear. I don't have any drive mapped to U, nor do I plug in any USB device that would appear as a U drive. And the U drive doesn't appear just once, it gets repeated more and more over time.

Example:

C:  D:  E:  G:  H:  K:  N:  P:  S:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:  U:

the icon for the U drive doesn't match any of my other local or mapped network drives and it has a ? on it.

**Comment by CodeIter** [comment] 2020-06-15 07:40
I found this solution https://www.sevenforums.com/tutorials/6969-drives-hide-show-empty-drives-computer-folder.html .
in windows explorer settings desactivate the option `hide empty letters`, click `apply`, reactivate it, click `ok`

**Comment by CanuckGamer** [comment] 2020-06-15 20:10
> I found this solution https://www.sevenforums.com/tutorials/6969-drives-hide-show-empty-drives-computer-folder.html .
> in windows explorer settings desactivate the option `hide empty letters`, click `apply`, reactivate it, click `ok`

But it's not an empty drive, it's a non-existent drive. I don't have a U drive on my machine.

**Comment by CodeIter** [comment] 2020-06-15 21:10
and i don't have letter `E: ` either, only in explorer++ show up as non-existent inaccessible drive.
now my explorer++ don't have letter `E:`.
Did you try this fix and it didn't work for your case ? if this not work for you, i hope you find a another fix.

**Comment by CanuckGamer** [comment] 2020-06-15 21:34
> Did you try this fix and it didn't work for your case ? if this not work for you, i hope you find a another fix.

I haven't seen the bug since I upgraded to the latest version.

**Comment by derceg** [comment] 2023-08-16 18:48
I haven't been able to reproduce this and since the code to add drives to the drives toolbar has changed since this issue was created (to prevent duplicate items being added at all) and CanuckGamer indicates they haven't seen the issue since upgrading, I'm going to close this issue.

**Closed by derceg** 2023-08-16 18:48 UTC
Labels: bug, unconfirmed
