### ISSUE TITLE
Same crash with removed usb key on first tab

### ISSUE THREAD

**Issue by abarbieriswlg** [derceg/explorerplusplus#454] opened 2024-05-31 09:02 UTC
Even the last build 1.5.2421 crashes if I:

- open the usb key root folder in THE FIRST tab
- close e++
- use "safely remove hardware" to remove the key
- unplug the key
- start e++ again

OS is Win11 23H2

Funny enough, the previous version crashed in all tabs, now only with the 1st. 

[Explorer++1.5.0.2421-31052024-101620.dmp](https://github.com/user-attachments/files/15510524/Explorer%2B%2B1.5.0.2421-31052024-101620.dmp)

Thanks

**Comment by derceg** [comment] 2024-06-01 06:50
Thanks, this is a duplicate of #453.

**Closed** 2024-06-01 06:50 UTC
Labels: bug, duplicate, crash
