### ISSUE TITLE
forgotten bookmarks

### ISSUE THREAD

**Issue by chezinut** [derceg/explorerplusplus#70] opened 2017-07-07 20:10 UTC
after restart all bookmarks are gone... i mean not  application bookmarks (they are OK)... dir bookmarks
and seems import export dont work in bookmark manager

**Comment by derceg** [comment] 2017-07-09 12:29
Thanks for the report. The bookmarks system is in the process of being rewritten, which is why it doesn't work at the moment. I'm closing this as a duplicate of #2.

**Closed by derceg** 2017-07-09 12:29 UTC
Labels: bug, duplicate
