### ISSUE TITLE
[1682 dev] Crash on opening "This PC" folder.

### ISSUE THREAD

**Issue by kettenfett** [derceg/explorerplusplus#275] opened 2020-10-16 08:10 UTC
**Describe the bug**

It crashes on opening "This PC" folder.
When you have "This PC" set as default folder to open on new tab, it will obviously also crash upon double click on tabbar (to open a new tab) or rightclick on tabbar->"newtab". 

**To Reproduce**
Open "This PC" any way you like.

**Additional context**
By testing app veyor versions, I determined that the regression happened somewhere between dev versions 1645 and 1650, although i can't tell which one exactly, because from 1645 to ..49 the program didn't start. In 1644, it still worked. 

I think #224 #245 #259 may be the culprit, since they're dealing with "This PC".

**Comment by sean-e** [comment] 2020-10-16 12:34
the referenced pull requests are not culprits since none have been accepted.  they are attempts to fix previously reported instances of this issue.

**Comment by sean-e** [comment] 2020-10-16 12:37
likely dupe of #218 and #246

**Comment by kettenfett** [comment] 2020-10-16 23:04
I see. Then I must have got it the wrong way round with the pull requests. I'm not too familiar with pull requests on github.

**Closed** 2021-01-11 04:54 UTC
Labels: bug
