### ISSUE TITLE
Right clicking an empty area causes crash

### ISSUE THREAD

**Issue by GeorgeHahn** [derceg/explorerplusplus#35] opened 2015-06-01 18:03 UTC
Reproduction:
- Open any directory and any view style
- Right click an empty area of the view

Additional details:
Windows 10 x64, build 10130

**Comment by GeorgeHahn** [comment] 2015-06-01 19:28
After some investigation, I concluded that this is caused by the OneDrive filesyncshell.dll.

I was able to overcome it by turning on SEH exception handling in the `Helper` project and wrapping the `QueryContextMenu` call in the `AddMenuEntries` function of `ContextMenuManager.cpp`:

```
HRESULT hr;
try {
    hr = itr->pContextMenuActual->QueryContextMenu(
        hMenu, iStartPos, iMinID + iOffset, iMaxID,
        CMF_NORMAL | CMF_EXPLORE);
}
catch (...) {
    // Swallow context menu error
    continue;
}
```

**Comment by JTB3** [comment] 2015-08-05 18:40
Verified that this critical crash behavior is still present in the official Windows 10 x64 release (build 10240).
Thx George for finding the workaroud.  Would be great to get this committed into a fresh build.  Otherwise it's a 'No-Go' for Win 10...

**Comment by macchky** [comment] 2015-11-25 10:38
Temp fix is Launch as Administrator

**Comment by linquize** [comment] 2015-11-25 10:50
Do Windows Explorer has such empty space to test with?

**Comment by derceg** [comment] 2015-12-26 06:58
It would be good to find out exactly what's going wrong. It's quite possible there's a bug within the context menu code, particularly if the menu item appears correctly in other file managers (I haven't tested this myself, but I would assume it does - would anybody be able to confirm?).

It's interesting that it works when run as an administrator, I'm not sure why that would be the case, and obviously we don't have access to the Onedrive source code.

@GeorgeHahn 
My concern with swallowing the exception is that it might result in an inconsistent state, which could lead to further crashes or corruption.

If anybody wants to debug through the code on Windows 10 and do some experimentation, that would be of great help. I'm happy to assist.

**Comment by juanitogan** [comment] 2016-01-16 05:13
I ended up here because the new File Explorer in Win 10 is killing me.  I get lost too easily scrolling the tree with its tiny indentations.  And I work a lot in the tree.  This right-click thing is almost a show stopper.  For now I have Admin permanently set in the Compatibility tab for the file.  I worry about the others frustrated with the new File Explorer and less savvy to figure out the workaround.  Anyhow, thank you for what looks to be a quality solution to my File Explorer pains.

**Comment by derceg** [comment] 2016-02-14 06:50
From some testing I've been doing, it looks like the OneDrive extension causes an access violation. It could be because of a bug in Explorer++, or a bug in OneDrive. Since the problem occurs inside the QueryContextMenu call, it would be difficult to figure out which is at fault.

I think the best way of handling this would be to blacklist the extension using its CLSID (which will at least stop the crashes). Then, if the issue is resolved in the future, the extension can be loaded again.

**Comment by Boiethios** [comment] 2016-10-13 12:33
Hello, the Explorer++ still crashes on Windows 8.x

When I right-click somewhere out of a file, it immediately crashes.

**Comment by endo64** [comment] 2016-10-25 08:55
I confirm @Boiethios, Explorer++ still crashes on Win 8.1 x64.
Is this fix included in the latest compiled version on web site?

**Comment by paulbrennanOJT** [comment] 2017-03-16 12:47
Confirmed that uninstalling OneDrive (if it is an option for you) does resolve the issue :)

**Comment by kenstuddy** [comment] 2017-06-11 13:10
Even though I already had OneDrive disabled via GPO, I still had this issue. I resolved this issue by renaming C:\Users\user\AppData\Local\Microsoft\OneDrive to C:\Users\user\AppData\Local\Microsoft\OneDrivebak.

**Closed** 2017-06-11 13:58 UTC
Labels: bug, critical

**Comment by endo64** [comment] 2017-06-17 10:10
@kenstuddy Disabling doesn't solve the crash issue, I completely uninstall OneDrive then issue solved. When you rename that folder your OneDrive installation still works normally?

**Comment by kenstuddy** [comment] 2017-06-17 12:31
I disabled OneDrive in GPO and from starting up, however the crash still happened until I renamed the OneDrive folder. However, as of June 11, this bug has been fixed.

**Comment by demahum** [comment] 2018-01-13 07:43
It would be good to solve this issue completely if possible (i.e. to be able to have both OneDrive and Explorer++ running).
