### ISSUE TITLE
Going to upper folder with focus lost

### ISSUE THREAD

**Issue by qwfpbj** [derceg/explorerplusplus#282] opened 2020-10-31 09:34 UTC
**Describe the bug**
Use backspace to go to upper folder ,while the focus is lost. The expected behavior is that the file explorer's focus is on the original folder when going to the upper folder.

**To Reproduce**
1. Go to any folder
2. Goes to the upper folder from menu or directly from typing backspace
3. The focus is lost. The focus is on the first file on the upper folder.

**Expected behavior**
The focus should be on the previously folder rather thatn on the first file on the upper folder.

**Crashes**
Please attach the associated crash dump. This file should be created in %temp% and be named something like Explorer++1.4.0.0-11102020-194414.dmp. Not attaching a crash dump may make it significantly more difficult to diagnose the cause of a crash.

**Screenshots**

**Version (please complete the following information):**
 - Explorer++ version: [e.g. 1.4.0.1616 dev (64-bit build)]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by sean-e** [comment] 2020-11-01 13:28
This seems related to or is a dupe of #212 ?

**Comment by qwfpbj** [comment] 2020-11-02 09:07
@sean-e I am sorry for the duplication.

**Comment by derceg** [comment] 2021-01-11 02:48
Duplicate of #212

**Closed by derceg** 2021-01-11 02:48 UTC
Labels: bug
