### ISSUE TITLE
The file viewer is blue

### ISSUE THREAD

**Issue by The-SamminAter** [derceg/explorerplusplus#236] opened 2020-06-09 19:47 UTC
**Describe the bug**
The file viewer in Explorer++ is blue. I've tried deleting `config.xml` (Explorer++ is being ran in portable mode), but that didn't make a difference. I may know what caused this, but I'm not sure.

**To Reproduce**
(I think this is how I caused it)
1. Try to resize/minimize the section at the bottom which shows device information

**Expected behavior**
The blue device information section to be minimized

**Screenshots**
![20200609_124214](https://user-images.githubusercontent.com/48739810/84192327-ac1d6500-aa4e-11ea-9691-46b4a3d4ec3f.png)

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1637
 - OS: Windows 10 2019 LTSC

**Comment by derceg** [comment] 2021-01-11 02:50
Duplicate of #233

**Closed by derceg** 2021-01-11 02:50 UTC
Labels: bug
