### ISSUE TITLE
Crash when switching to dark mode on ARM64

### ISSUE THREAD

**Issue by einfallen** [derceg/explorerplusplus#480] opened 2024-09-19 02:10 UTC
[Explorer++1.5.0.2483-19092024-100845.dmp](https://github.com/user-attachments/files/17052509/Explorer%2B%2B1.5.0.2483-19092024-100845.dmp)

**Describe the crash**
A clear and concise description of the crash.

**To Reproduce**
Steps to reproduce the crash:
4. Explorer++ crashes

**Screenshots**

**Version (please complete the following information):**
 - Explorer++ version: [e.g. 1.4.0.1616 dev (64-bit build)]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by derceg** [comment] 2024-09-19 05:00
It looks like this is a duplicate of #478.

@einfallen Could you please try the build linked in that issue (see https://github.com/derceg/explorerplusplus/issues/478#issuecomment-2354487686), check whether it fixes the crash and leave a comment there. I don't have an ARM64 device, so I have no simple way of verifying whether or not the issue is fixed.

**Closed by derceg** 2024-09-19 05:00 UTC
Labels: bug, crash
