### ISSUE TITLE
tabs on windows 10 high DPI very small

### ISSUE THREAD

**Issue by chen6677** [derceg/explorerplusplus#105] opened 2018-03-15 04:49 UTC
I found that on windows 10 the tabs was very small and quite hard for user to click.

![image](https://user-images.githubusercontent.com/18516591/37449393-06fe1c80-2865-11e8-8599-97792d7b7f42.png)

**Comment by derceg** [comment] 2021-01-11 02:38
Duplicate of #150

**Closed** 2021-01-11 02:38 UTC
