### ISSUE TITLE
auto refresh file list 

### ISSUE THREAD

**Issue by long-nguyenxuan** [derceg/explorerplusplus#164] opened 2019-09-29 15:13 UTC
## Current 
File list doesn't got refreshed so new file won't show until user press `Ctrl-R` 
## Expect 
File list got auto refreshed so new file got show whenever it created.

**Comment by derceg** [comment] 2021-01-11 07:27
This should work already for filesystem folders. For virtual folders, the approach outlined in #106 would be needed. This issue is effectively a duplicate of that.

**Closed by derceg** 2021-01-11 07:27 UTC
