### ISSUE TITLE
Explorer++ hangs on opening folders

### ISSUE THREAD

**Issue by tanooki-games** [derceg/explorerplusplus#98] opened 2018-01-10 16:03 UTC
Explorer++ often hangs for a few seconds, when opening folders.  No idea, why this happens, but it makes it less fun to use E++.

**Comment by samaursa** [comment] 2018-01-23 14:13
This is because Explorer++ has a tooltip that also has the folder size:

![image](https://user-images.githubusercontent.com/817849/35280250-99a8c884-001d-11e8-9b34-e0119327212d.png)

A suggested fix would be to allow the user to remove the option for having the tooltip.

**Comment by samaursa** [comment] 2018-01-23 14:16
And here's how to fix that issue:

![image](https://user-images.githubusercontent.com/817849/35280395-19af3e6e-001e-11e8-9c77-2e3c9cd45f37.png)

**Comment by gembutterfly** [comment] 2018-01-25 09:51
Thanks, that really helped. It doesn't fix the issue though. Guess the folder calculations could be done in another thread. Thanks for the workaround.

**Comment by samaursa** [comment] 2018-01-25 14:15
Np! I agree, it's not a _fix_. Spawning a thread for this kind of work would be ideal.

**Comment by derceg** [comment] 2021-01-11 03:22
Although this issue has some discussion in it, I'll close it as a duplicate of #283, since I did some recent work for that to move the folder enumeration to a background thread.

**Closed by derceg** 2021-01-11 03:22 UTC
