### ISSUE TITLE
Default Columns for "Detail View" not saving...

### ISSUE THREAD

**Issue by IBIT-ZEE** [derceg/explorerplusplus#232] opened 2020-05-21 12:49 UTC
v1.4.0.1637

Tools->Option->Default Settings->[Default Columns... (for details)]

is not saving... nor applying...

**Comment by sean-e** [comment] 2020-05-22 02:52
looks like dupe of #215

**Comment by derceg** [comment] 2021-01-11 03:42
Duplicate of #215

**Closed by derceg** 2021-01-11 03:42 UTC
Labels: bug
