### ISSUE TITLE
Text and Icons rendering are not proper

### ISSUE THREAD

**Issue by stenalpjolly** [derceg/explorerplusplus#100] opened 2018-02-23 04:57 UTC
![image](https://user-images.githubusercontent.com/8219855/36578544-edd9b746-1883-11e8-8f17-6ac66bdba5e4.png)

As you can see the text and icons seem so pixelated. I don't know whether its related to subpixel/aliasing issue.

**Comment by derceg** [comment] 2021-01-11 02:35
This is probably a DPI scaling issue. Duplicate of #150.

**Closed** 2021-01-11 02:35 UTC
