### ISSUE TITLE
Dark Color Scheme

### ISSUE THREAD

**Issue by dougransom** [derceg/explorerplusplus#308] opened 2021-01-19 19:11 UTC
I suggest adding a dark color scheme to use at night, that once can easily switch too, with readable default colors.

**Comment by dougransom** [comment] 2021-01-19 19:13
i can't figure out how to change the label, it should be ehancment, not bug.

**Comment by i2** [comment] 2021-01-20 01:48
If you mean dark theme, check this out: https://github.com/derceg/explorerplusplus/issues/115

**Comment by derceg** [comment] 2021-01-20 07:08
Duplicate of #115

**Closed by derceg** 2021-01-20 07:08 UTC
Labels: enhancement
