### ISSUE TITLE
Explorer++ currsor should remember last folder when backing up

### ISSUE THREAD

**Issue by burakyuksek** [derceg/explorerplusplus#267] opened 2020-08-23 19:18 UTC
Let's say I'm in a folder with 3 other folders.
I click on the second folder.
I press backspace. File explorer returns the currsor to the second folder but explorer++ doesn't. It would be nice if it would.

**Comment by sean-e** [comment] 2020-08-24 12:03
looks like possible dupe of #212 addressed in PR #223

**Comment by derceg** [comment] 2021-01-11 02:48
Duplicate of #212

**Closed by derceg** 2021-01-11 02:48 UTC
