### ISSUE TITLE
request: when a new tab of the same type as the current tab is opened, use the same column widths

### ISSUE THREAD

**Issue by sean-e** [derceg/explorerplusplus#217] opened 2020-04-25 04:11 UTC
Request: when a directory in a tab in detail view of general items is selected and a new tab is created using the selected directory (via ctrl+t), initialize the column widths of the new tab to be the same as the previously active tab.

(Force new tab is off.)

1.4.0.1592

**Comment by jczanfona** [comment] 2020-04-25 14:15
Solved with [v1.4.0.1594](https://github.com/derceg/explorerplusplus#latest-builds)
Can you test it?

**Comment by sean-e** [comment] 2020-04-25 21:40
> 
> 
> Solved with [v1.4.0.1594](https://github.com/derceg/explorerplusplus#latest-builds)
> Can you test it?

What is the basis for your statement that it was solved?
What change fixed it?

**Comment by jczanfona** [comment] 2020-04-27 07:27
Remember to press in the menu: View - Save Column Layout as Default" with only have one tab, and then try to open others.
Last version is [v1.4.0.1606](https://github.com/derceg/explorerplusplus#latest-builds)

If you think the problem is solved, you can close this ticket.

**Comment by sean-e** [comment] 2020-04-27 14:47
I think my PR addresses the request without having to change the default.

**Closed** 2020-10-31 22:59 UTC
