### ISSUE TITLE
Bookmarks Toolbar does not work?

### ISSUE THREAD

**Issue by silaoA** [derceg/explorerplusplus#205] opened 2020-03-17 07:20 UTC
explorer++ version : 1.3.5_x64 portable。
Windows : Windows 10 1903 Enterprise  build 18362.657  64 bit。

I'm new user of  explorer++ and have read documentation. I have added some bookmarks and checked the box "Show on Bookmarks in Toolbar"， but all of them show in the menu "**Bookmarks**" instead of  Bookmarks Toolbar.  The Bookmarks Toolbar is empty. 
I'm eagerly expecting an solution. many thanks.

**Comment by derceg** [comment] 2020-06-01 07:58
I'm not sure of the cause of this, but the bookmarks system has been rewritten for version 1.4.0 (which is in beta) and bookmark bugs specific to 1.3.5 won't be fixed, unfortunately.

**Closed by derceg** 2020-06-01 07:58 UTC

**Comment by stibu81** [comment] 2021-02-16 10:10
I also have the issue that the bookmarks toolbar is not visible. This seems to be connected to the Font Size Settings in Windows 10: when I set the font size to 100%, I can see the bookmarks toolbar, but when I set to font size to 109% or more, the toolbar is  empty. It still takes up some space, but I can not see the icons:

![image](https://user-images.githubusercontent.com/7131000/108048237-114a4100-7047-11eb-8462-cebba81875a0.png)

I understand that this won't be fixed in the current release.  But I would appreciate it if larger font size could be supported in the coming release.

@silaoA Have you also increased the font size in Windows.

**Comment by stibu81** [comment] 2021-02-16 10:54
I have now installed 1.4.0.1748 beta (64-bit build) and can confirm that to Bookmarks Toolbar is visible also if the Windows font size is set to 160%. (I haven't tried even larger font sizes.)

**Comment by silaoA** [comment] 2021-03-02 05:31
> 
> 
> I also have the issue that the bookmarks toolbar is not visible. This seems to be connected to the Font Size Settings in Windows 10: when I set the font size to 100%, I can see the bookmarks toolbar, but when I set to font size to 109% or more, the toolbar is empty. It still takes up some space, but I can not see the icons:
> 
> ![image](https://user-images.githubusercontent.com/7131000/108048237-114a4100-7047-11eb-8462-cebba81875a0.png)
> 
> I understand that this won't be fixed in the current release. But I would appreciate it if larger font size could be supported in the coming release.
> 
> @silaoA Have you also increased the font size in Windows.

yes, font size is set to 150% by default because of display definition.
