### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by tanhangbo** [derceg/explorerplusplus#383] opened 2023-04-01 11:38 UTC
Explorer++ is the **best file manager** in this world. I'd like to change to font size of the 'detail view' and folder treeview, but there is no option in settings.

**Comment by derceg** [comment] 2023-06-17 03:47
This is something I'm actively working on at the moment, but I'll close this issue as it's a duplicate of #27.

**Closed by derceg** 2023-06-17 03:47 UTC
