### ISSUE TITLE
Crash on right click

### ISSUE THREAD

**Issue by KrunchMuffin** [derceg/explorerplusplus#64] opened 2017-01-30 16:01 UTC
Windows 10

When I drill into a directory and right click the right pane in white area, e++ crashes. I tried to look and see it there was an option for debug logs, but couldn't find anything.

**Comment by derceg** [comment] 2017-03-04 13:07
Thanks for the report. I'll close this for now, as it's likely a duplicate of #35.

**Closed by derceg** 2017-03-04 13:07 UTC
