### ISSUE TITLE
"Incorrect layouts in large DPI mode"

### ISSUE THREAD

**Issue by n-o-o-b** [derceg/explorerplusplus#66] opened 2017-05-29 11:44 UTC
Hi, 

Is there any chance you could fix the issue and implement the suggestions detailed in this forum thread: https://explorerplusplus.com/forum/viewtopic.php?f=5&t=1012?

I'm using the 64-bit version and it looks very similar in 2017, the text in the address bar is not quite centred and some of the fonts are quite small, as you can see here:

![image](https://cloud.githubusercontent.com/assets/19697175/26548463/4394bb14-446c-11e7-9bb9-cb20f44606dc.png)

**Comment by derceg** [comment] 2021-01-11 02:37
Duplicate of #150

**Closed by derceg** 2021-01-11 02:38 UTC
Labels: bug
