### ISSUE TITLE
Issue with opening shortcuts to drives

### ISSUE THREAD

**Issue by vladaurosh** [derceg/explorerplusplus#229] opened 2020-05-05 22:49 UTC
Hello.
I was using latest stable Explorer++ (1.3.5 x64) for some time (in portable mode), on Windows 10 x64 and after some time I've upgrade to at  that time latest dev version (1.4.0.831 x64).

I am using it as explorer replacement.
There's issue with opening shortcuts to drives. I have shortcut to D: drive and latest explorer++ is opening but going to default new tab folder (This PC).
Same issue is happening on Windows 7 x64.
Latest stable 1.3.5 x64 doesn't have this issue.

This can be reproduced from cmd, for example:
`start d:`
which should open explorer++ in D drive.
On the other hand, if I type in cmd:
`start %APPDATA%`
this works fine and opens C:\Users\User\AppData\Roaming

Also opening this from cmd:
`"C:\Program Files\explorer++\Explorer++.exe" "d:"`
works as expected (opens D drive).

If I create shortcut to some dir (for example C:\Windows), it works fine. This also works:
`start c:\Windows`

So looks like issue is just with opening root of drives.

I tried several previous versions and looks like 1.4.0.796 doesn't have this issue, and next one (1.4.0.799) has it.
This is what was added/changed in that version. 
```
Use CLI11 to parse command line options
This has a few advantages over the previous manual approach:

- The option parsing is handled by the library, so it doesn't need to be
done manually.
- More detailed help usage is now shown when passing the -h/--help flag.
Information about each of the available options is shown.
- Options can be marked as mutually exclusive. This is done with the
--remove_as_default and --set_as_default flags, for example.
- Options can be passed in in windows style (e.g. /help).
- Although not used at the moment, the library also offers other
features, such as the ability to validate and transform input values
```

Related commit https://github.com/derceg/explorerplusplus/commit/b69ef8af3794e7b9655d8cde75ec3c546df4c1e5

I tried latest dev version 1.4.0.1609 and issue is still present.

**Comment by derceg** [comment] 2020-05-28 22:40
Duplicate of #202.

**Closed by derceg** 2020-05-28 22:40 UTC
