### ISSUE TITLE
Issues in portable mode

### ISSUE THREAD

**Issue by DeyanVasilev** [derceg/explorerplusplus#83] opened 2017-10-25 10:13 UTC
When in portable mode, no bookmarks are stored in Config.xml file when bookmarking open tabs.
Portable mode also cannot be unchecked once you have the Config.xml file created.

Explorer++ version is 1.4.0.105 64 bit Unicode Jul build@ Jul 20 2017 01:31:14

**Comment by tomiia** [comment] 2018-04-24 20:47
if you have that bug, simply remove the Config.xml file while explorer++ is runing, change the option and close it
i did that 2min ago and it was perfect
Explorer++ 1.4.156 64bit

**Comment by atmMokyu** [comment] 2019-03-12 04:59
It will not start up when running in portable mode.

1.4.0.666 (64-bit Unicode build) Build Date: Mar 11 2019 14:19:07

1. Clean Copy To Folder
2. Run Explorer++
3. Tools -> Options -> General
4. Check to Run in portable mode.
5. Close Explore++
6. It does not start Run Explorer++

**Comment by derceg** [comment] 2019-03-12 09:49
I've done a quick test locally with the config.xml file and it works. What are the contents of your config.xml file?

**Comment by atmMokyu** [comment] 2019-03-12 10:09
I will attach a sample.

[config.zip](https://github.com/derceg/explorerplusplus/files/2956252/config.zip)

**Comment by atmMokyu** [comment] 2019-03-12 10:15
It seems that the ToolbarState button value is not saved correctly.

**Comment by WildByDesign** [comment] 2019-04-03 13:59
**ToolbarState settings corruption (config.xml) in Portable Mode causing Explorer++ to not launch correctly:**

I have experienced this issue as well and would like to provide some more detail and a "temporary" workaround.

This issue has to do with ToolbarState settings becoming corrupt in Portable Mode config.xml file in recent AppVeyor builds of Explorer++ and is not an issue with the old 1.3.5 release. The nightly builds on AppVeyor are so fantastic, so it would be great to see a resolution to this issue.

**Prior to first launch:**

`<Setting name="ToolbarState" Button0="Back" Button1="Forward" Button2="Up" Button3="Separator" Button4="Folders" Button5="Separator" Button6="Cut" Button7="Copy" Button8="Paste" Button9="Delete" Button10="Delete permanently" Button11="Properties" Button12="Search" Button13="Separator" Button14="New Folder" Button15="Copy To" Button16="Move To" Button17="Separator" Button18="Views" Button19="Show Command Prompt" Button20="Refresh" Button21="Separator" Button22="Bookmark the current tab" Button23="Organize Bookmarks"/>`

**After first launch:**

`<Setting name="ToolbarState" Button0="" Button1="" Button2="" Button3="" Button4="" Button5="" Button6="" Button7="" Button8="" Button9="" Button10="" Button11="" Button12="" Button13="" Button14="" Button15="" Button16="" Button17="" Button18="" Button19="" Button20="" Button21="" Button22="" Button23=""/>`

**After ToolbarState corruption:**

Explorer++ executes and stays in memory, however, there is no visible GUI as the process just seems to be a ghost process with no way to interact with UI.

**What I have observed:**

You can remove that entire ToolbarState line from the config.xml and that will allow Explorer++ to start up and run correctly. However, that will corrupt the ToolbarState line again and therefore subsequent launches of Explorer++ with fail again with ghost processes and no visible UI to interact with. This becomes and endless cycle.

Even putting the correct ToolbarState line settings in again will corrupt again and again.

**"Temporary" Workaround:**

This is for those who want to continue using Explorer++ nightly builds in Portable Mode.

Get your portable mode settings to the way you like them. This requires fixing the config.xml file many times by removing the ToolbarState line and starting Explorer++ again multiple times. You will also likely have to kill the explorer++.exe processes in Task Manager.

Once you have your portable mode settings config.xml file the way you like it and everything is working great, you can proceed to temporary workaround.

You need to add a Deny Write ACL to the config.xml file. The Deny rule will be priority over any of the Allow rules. I just do a simple Deny for Write access only and only for my specific username.

This will make it so that no more changes can occur to the config.xml file and therefore it will no longer become corrupt upon subsequent Explorer++ launches. You are good to go now. If you need to make any changes to your Explorer++ settings, you will need to remove that Deny Write ACL to the config.xml file, get your settings the way you like them again, remove the ToolbarState line again, and add the Deny Write ACL once again to lock down your settings so that you can continue using Explorer++ in portable mode.

**Comment by stkb** [comment] 2019-04-03 17:45
https://github.com/derceg/explorerplusplus/blob/5660ff3e9bd7bc5fabc87a753fc026122eda6e70/Explorer%2B%2B/Explorer%2B%2B/XMLSettings.cpp#L608-L612

This happens because the `szButtonName` variable is written as the xml attribute value without having being set, so just random garbage bytes are written to the xml file.

Lines 609-610, where the variable used to be set, were commented in out in 4a651cf4cb307b822b4ecd59d29c3843126da80b, where @derceg started moving toolbar code into a separate class (inc the `LookupToolbarButtonTextID` function, but this was left unfinished. It should be possible to apply a quick-and-dirty fix to this.

**Comment by WildByDesign** [comment] 2019-11-18 13:47
I can confirm that this latest commit has fixed the issues in Portable mode regarding the crash related to customization of the toolbar icon placement as well as the customization itself. Both issues are fixed from what I can tell so far.

I have not tested the bookmark issue from the original issue posted though.

**Comment by atmMokyu** [comment] 2019-11-19 02:34
It was able to operate normally in Portable mode.

**Closed** 2021-01-11 03:06 UTC
